<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HabilidadeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
DB::table('habilidades')->insert(['id'=>1,'desc'=>'(MA03) Comparar quantidades de objetos de dois conjuntos, por estimativa e/ou por correspondência (um a um, dois a dois, entre outros), para indicar “tem mais”, “tem menos” ou “tem a mesma quantidade”, indicando, quando for o caso, quantos a mais e quantos a menos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>2,'desc'=>'(MA04) Compor e decompor números naturais de até três ordens, com suporte de material manipulável, por meio de diferentes adições.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>3,'desc'=>'(MA07) Resolver e elaborar problemas de multiplicação (por 2, 3, 4 e 5) com a ideia de adição de parcelas iguais por meio de estratégias e formas de registro pessoais, utilizando ou não suporte de imagens e/ou material manipulável.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>4,'desc'=>'(MA08) Resolver e elaborar problemas envolvendo dobro, metade, triplo e terça parte, com o suporte de imagens ou material manipulável, utilizando estratégias pessoais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>5,'desc'=>'(MA11) Descrever os elementos ausentes em sequências repetitivas e em sequências recursivas de números naturais, objetos ou figuras.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>6,'desc'=>'(MA12) Identificar e registrar, em linguagem verbal ou não verbal, a localização e os deslocamentos de pessoas e de objetos no espaço, considerando mais de um ponto de referência, e indicar as mudanças de direção e de sentido.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>7,'desc'=>'(MA16) Estimar, medir e comparar comprimentos de lados de salas (incluindo contorno) e de polígonos, utilizando unidades de medida não padronizadas e padronizadas (metro, centímetro e milímetro) e instrumentos adequados.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>8,'desc'=>'(MA18) Indicar a duração de intervalos de tempo entre duas datas, como dias da semana e meses do ano, utilizando calendário, para planejamentos e organização de agenda.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>9,'desc'=>'D10-Q1 Num problema, estabelecer trocas entre cédulas e moedas do sistema monetário brasileiro, em função de seus valores.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>10,'desc'=>'D10-Q2 Utilizar relações métricas do triângulo retângulo para resolver problemas significativos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>11,'desc'=>'D11-Q2 Reconhecer círculo/circunferência, seus elementos e algumas de suas relações.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>12,'desc'=>'D12-Q1 Resolver problema envolvendo o cálculo ou estimativa de áreas de figuras planas, desenhadas em malhas quadriculadas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>13,'desc'=>'D12-Q2 Resolver problema envolvendo o cálculo de perímetro de figuras planas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>14,'desc'=>'D13-Q1 Reconhecer e utilizar características do sistema de numeração decimal, tais como agrupamentos e trocas na base 10 e princípio do valor posicional.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>15,'desc'=>'D13-Q2 Resolver problema envolvendo o cálculo de área de figuras planas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>16,'desc'=>'D14-Q1 Identificar a localização de números naturais na reta numérica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>17,'desc'=>'D14-Q2 Resolver problema envolvendo noções de volume.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>18,'desc'=>'D15-Q1 Reconhecer a decomposição de números naturais nas suas diversas ordens.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>19,'desc'=>'D15-Q2 Resolver problema utilizando relações entre diferentes unidades de medida.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>20,'desc'=>'D16-Q1 Reconhecer a composição e a decomposição de números naturais em sua forma polinomial.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>21,'desc'=>'D16-Q2 Identificar a localização de números inteiros na reta numérica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>22,'desc'=>'D17-Q1 Calcular o resultado de uma adição ou subtração de números naturais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>23,'desc'=>'D17-Q2 Identificar a localização de números racionais na reta numérica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>24,'desc'=>'D18-Q1 Calcular o resultado de uma multiplicação ou divisão de números naturais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>25,'desc'=>'D18-Q2 Efetuar cálculos com números inteiros, envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>26,'desc'=>'D19-Q1 Resolver problema com números naturais, envolvendo diferentes significados da adição ou subtração: juntar, alteração de um estado inicial (positiva ou negativa), comparação e mais de uma transformação (positiva ou negativa).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>27,'desc'=>'D19-Q2 Resolver problema com números naturais, envolvendo diferentes significados das operações (adição, subtração, multiplicação, divisão, potenciação).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>28,'desc'=>'D1-Q1 Identificar a localização/movimentação de objeto em mapas, croquis e outras representações gráficas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>29,'desc'=>'D1-Q2 Identificar a localização/movimentação de objeto em mapas, croquis e outras representações gráficas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>30,'desc'=>'D20-Q1 Resolver problema com números naturais, envolvendo diferentes significados da multiplicação ou divisão: multiplicação comparativa, ideia de proporcionalidade, configuração retangular e combinatória.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>31,'desc'=>'D20-Q2 Resolver problema com números inteiros envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>32,'desc'=>'D21-Q1 Identificar diferentes representações de um mesmo número racional	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>33,'desc'=>'D21-Q1 Identificar diferentes representações de um mesmo número racional.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>34,'desc'=>'D21-Q2 Reconhecer as diferentes representações de um número racional.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>35,'desc'=>'D22-Q1 Identificar a localização de números racionais representados na forma decimal na reta numérica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>36,'desc'=>'D22-Q2 Identificar fração como representação que pode estar associada a diferentes significados.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>37,'desc'=>'D23-Q1 Resolver problema utilizando a escrita decimal de cédulas e moedas do sistema monetário brasileiro.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>38,'desc'=>'D23-Q2 Identificar frações equivalentes.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>39,'desc'=>'D24-Q1 Identificar fração como representação que pode estar associada a diferentes significados.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>40,'desc'=>'D24-Q2 Reconhecer as representações decimais dos números racionais como uma extensão do sistema de numeração decimal, identificando a existência de "ordens" como décimos, centésimos e milésimos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>41,'desc'=>'D25-Q1 Resolver problema com números racionais expressos na forma decimal envolvendo diferentes significados da adição ou subtração.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>42,'desc'=>'D26-Q1 Resolver problema envolvendo noções de porcentagem (25%, 50%, 100%).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>43,'desc'=>'D26-Q2 Resolver problema com números racionais envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>44,'desc'=>'D27 Efetuar cálculos simples com valores aproximados de radicais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>45,'desc'=>'D27-Q1 Ler informações e dados apresentados em tabelas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>46,'desc'=>'D27-Q2 Efetuar cálculos simples com valores aproximados de radicais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>47,'desc'=>'D28-Q1 Ler informações e dados apresentados em gráficos (particularmente em gráficos de colunas).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>48,'desc'=>'D28-Q2 Resolver problema que envolva porcentagem.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>49,'desc'=>'D29-Q2 Resolver problema que envolva variação proporcional, direta ou inversa, entre grandezas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>50,'desc'=>'D2-Q1 Identificar propriedades comuns e diferenças entre poliedros e corpos redondos, relacionando figuras tridimensionais com suas planificações.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>51,'desc'=>'D2-Q2 Identificar propriedades comuns e diferenças entre figuras bidimensionais e tridimensionais, relacionando-as com as suas planificações.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>52,'desc'=>'D30-Q2 Calcular o valor numérico de uma expressão algébrica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>53,'desc'=>'D31-Q2 Resolver problema que envolva equação do 2º grau.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>54,'desc'=>'D32-Q2 Identificar a expressão algébrica que expressa uma regularidade observada em sequências de números ou figuras (padrões).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>55,'desc'=>'D33-Q2 Identificar uma equação ou inequação do 1º grau que expressa um problema.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>56,'desc'=>'D34-Q2 Identificar um sistema de equações do 1º grau que expressa um problema.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>57,'desc'=>'D35-Q2 Identificar a relação entre as representações algébrica e geométrica de um sistema de equações do 1º grau.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>58,'desc'=>'D36-Q2 Resolver problema envolvendo informações apresentadas em tabelas e/ou gráficos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>59,'desc'=>'D37-Q2 Associar informações apresentadas em listas e/ou tabelas simples aos gráficos que as representam e vice-versa.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>60,'desc'=>'D3-Q1 Identificar propriedades comuns e diferenças entre figuras bidimensionais pelo número de lados, pelos tipos de ângulos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>61,'desc'=>'D3-Q2 Identificar propriedades de triângulos pela comparação de medidas de lados e ângulos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>62,'desc'=>'D4-Q1 Identificar quadriláteros observando as posições relativas entre seus lados (paralelos, concorrentes, perpendiculares).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>63,'desc'=>'D5-Q1 Reconhecer a conservação ou modificação de medidas dos lados, do perímetro, da área em ampliação e/ou redução de figuras poligonais usando malhas quadriculadas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>64,'desc'=>'D5-Q2 Reconhecer a conservação ou modificação de medidas dos lados, do perímetro, da área em ampliação e/ou redução de figuras poligonais usando malhas quadriculadas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>65,'desc'=>'D6-Q1 Estimar a medida de grandezas utilizando unidades de medida convencionais ou não.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>66,'desc'=>'D6-Q2 Reconhecer ângulos como mudança de direção ou giros, identificando ângulos retos e não- retos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>67,'desc'=>'D7-Q1 Resolver problemas significativos utilizando unidades de medida padronizadas como km/m/ cm/mm, kg/g/mg, l/ml.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>68,'desc'=>'D7-Q2 Reconhecer que as imagens de uma figura construída por uma transformação homotética são semelhantes, identificando propriedades e/ou medidas que se modificam ou não se alteram.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>69,'desc'=>'D8-Q2 Resolver problema utilizando propriedades dos polígonos (soma de seus ângulos internos, número de diagonais, cálculo da medida de cada ângulo interno nos polígonos regulares).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>70,'desc'=>'D8-Q1 Estabelecer relações entre unidades de medida de tempo.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>71,'desc'=>'D9-Q1 Estabelecer relações entre o horário de início e término e/ou o intervalo da duração de um evento ou acontecimento.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>72,'desc'=>'D9-Q2 Interpretar informações apresentadas por meio de coordenadas cartesianas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>73,'desc'=>'H1 – Associar a contagem de coleções de objetos à representação numérica das suas respectivas quantidades	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>74,'desc'=>'H10 - Resolver problemas que envolvam as ideias da divisão	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>75,'desc'=>'H11 – Identificar figuras geométricas planas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>76,'desc'=>'H12 – Reconhecer as representações de figuras geométricas espaciais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>77,'desc'=>'H13 – Comparar e ordenar comprimentos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>78,'desc'=>'H14 – Identificar e relacionar cédulas e moedas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>79,'desc'=>'H15 - Identificar, comparar, relacionar e ordenar tempo em diferentes sistemas de medida.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>80,'desc'=>'H16 - Ler resultados de medições Grandezas de comprimento, massa, capacidade, temperatura.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>81,'desc'=>'H17 – Identificar informações apresentadas em tabelas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>82,'desc'=>'H18– Identificar informações apresentadas em gráficos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>83,'desc'=>'H2 –Associar a denominação do número a sua respectiva representação simbólica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>84,'desc'=>'H3 – Comparar ou ordenar quantidades pela contagem para identificar igualdade ou desigualdade numérica.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>85,'desc'=>'H4 – Comparar ou ordenar números naturais.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>86,'desc'=>'H5 - Compor e decompor números.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>87,'desc'=>'H6 - Resolver problemas que demandam as ações de juntar, separar, acrescentar e retirar quantidades.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>88,'desc'=>'H7 - Resolver problemas que demandam as ações de comparar e completar quantidades.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>89,'desc'=>'H8 Cálculo de adições e subtrações.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>90,'desc'=>'H9 - Resolver problemas que envolvam as ideias da multiplicação.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>91,'desc'=>'Q1 D26 Resolver problema envolvendo noções de porcentagem (25%, 50%, 100%).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>92,'desc'=>'Q1 D27 Ler informações e dados apresentados em tabelas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>93,'desc'=>'Q2 D14 Resolver problema envolvendo noções de volume.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>94,'desc'=>'Q2 D26 Resolver problema com números racionais envolvendo as operações (adição, subtração, multiplicação, divisão, potenciação).	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>95,'desc'=>'Q2 D29 Resolver problema que envolva variação proporcional, direta ou inversa, entre grandezas.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>96,'desc'=>'Q2 D36 Resolver problema envolvendo informações apresentadas em tabelas e/ou gráficos.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>97,'desc'=>'Q2 D37 Associar informações apresentadas em listas e/ou tabelas simples aos gráficos que as representam e vice-versa.	 ','disciplinas_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>98,'desc'=>'(EF12LP18) Apreciar poemas e outros textos versificados, observando rimas, sonoridades, jogos de palavras, reconhecendo seu pertencimento ao mundo imaginário e sua dimensão de encantamento, jogo e fruição.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>99,'desc'=>'(EF15LP01) Identificar a função social de textos que circulam em campos da vida social dos quais participa cotidianamente (a casa, a rua, a comunidade, a escola) e nas mídias impressa, de massa e digital, reconhecendo para que foram produzidos, onde circulam, quem os produziu e a quem se destinam.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>100,'desc'=>'(EF15LP14) Construir o sentido de histórias em quadrinhos e tirinhas, relacionando imagens e palavras e interpretando recursos gráficos (tipos de balões, de letras, onomatopeias).	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>101,'desc'=>'(EF15LP15) Reconhecer que os textos literários fazem parte do mundo do imaginário e apresentam uma dimensão lúdica, de encantamento, valorizando-os, em sua diversidade cultural, como patrimônio artístico da humanidade.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>102,'desc'=>'D1 Localizar informações explícitas em um texto	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>103,'desc'=>'D10 Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>104,'desc'=>'D10 Identificar o conflito gerador do enredo e os elementos que constroem a narrativa	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>105,'desc'=>'D11 Distinguir um fato da opinião relativa a esse fato.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>106,'desc'=>'D11 Estabelecer relação causa/consequência entre partes e elementos do texto	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>107,'desc'=>'D12 Estabelecer relações lógico-discursivas presentes no texto, marcadas por conjunções, advérbios etc.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>108,'desc'=>'D12 Identificar a finalidade de textos de diferentes gêneros	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>109,'desc'=>'D13 Identificar as marcas linguísticas que evidenciam o locutor e o interlocutor de um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>110,'desc'=>'D13 Identificar efeitos de ironia ou humor em textos variados.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>111,'desc'=>'D14 Distinguir um fato da opinião relativa a esse fato.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>112,'desc'=>'D14 Identificar o efeito de sentido decorrente do uso da pontuação e de outras notações.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>113,'desc'=>'D15 Estabelecer relações lógico-discursivas presentes no texto, marcadas por conjunções, advérbios etc.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>114,'desc'=>'D15 Reconhecer diferentes formas de tratar uma informação na comparação de textos que tratam do mesmo tema, em função das condições em que ele foi produzido e daquelas em que será recebido.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>115,'desc'=>'D16 Identificar efeitos de ironia ou humor em textos variados.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>116,'desc'=>'D17 Reconhecer o efeito de sentido decorrente do uso da pontuação e de outras notações	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>117,'desc'=>'D18 Reconhecer o efeito de sentido decorrente da escolha de uma determinada palavra ou expressão	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>118,'desc'=>'D19 Reconhecer o efeito de sentido decorrente da exploração de recursos ortográficos e/ou morfossintáticos.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>119,'desc'=>'D2 Estabelecer relações entre partes de um texto, identificando repetições ou substituições que contribuem para a continuidade de um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>120,'desc'=>'D20 Reconhecer diferentes formas de tratar uma informação na comparação de textos que tratam do mesmo tema em função das condições em que ele foi produzido e daquelas em que será recebido.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>121,'desc'=>'D21 Reconhecer posições distintas entre duas ou mais opiniões relativas ao mesmo fato ou ao mesmo tema.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>122,'desc'=>'D3 Inferir o sentido de uma palavra ou expressão.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>123,'desc'=>'D4 Inferir uma informação implícita em um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>124,'desc'=>'D5 Interpretar texto com auxílio de material gráfico diverso (propagandas, quadrinhos, foto etc.).	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>125,'desc'=>'D6 Identificar o tema de um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>126,'desc'=>'D7 Identificar a tese de um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>127,'desc'=>'D7 Identificar o conflito gerador do enredo e os elementos que constroem a narrativa.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>128,'desc'=>'D8 Estabelecer relação causa/consequência entre partes e elementos do texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>129,'desc'=>'D8 Estabelecer relação entre a tese e os argumentos oferecidos para sustentá-la	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>130,'desc'=>'D9 Diferenciar as partes principais das secundárias em um texto.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>131,'desc'=>'D9 Identificar a finalidade de textos de diferentes gêneros.	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>132,'desc'=>'H1. Ler palavras com estrutura silábica canônica	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>133,'desc'=>'H10. Grafar palavras com correspondências regulares diretas	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>134,'desc'=>'H11. Grafar palavras com correspondências regulares contextuais entre letras ou grupos de letras e seu valor sonoro	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>135,'desc'=>'H2. Ler palavras com estrutura silábica não canônica	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>136,'desc'=>'H3. Reconhecer a finalidade do texto	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>137,'desc'=>'H4. Localizar informações explícitas em textos	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>138,'desc'=>'H5. Compreender os sentidos de palavras e expressões em textos	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>139,'desc'=>'H6. Realizar inferências a partir da leitura de textos verbais	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>140,'desc'=>'H7. Realizar inferências a partir da leitura de textos que articulem a linguagem verbal e não verbal	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>141,'desc'=>'H8. Identificar o assunto de um texto	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);
DB::table('habilidades')->insert(['id'=>142,'desc'=>'H9. Estabelecer relações entre partes de um texto marcadas por elementos coesivos	 ','disciplinas_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);

    }
}
