<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;


class TurmasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('turmas')->insert(['id'=>	49398	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49404	,'TURMA'=>'22','DESCR_TURMA'=>'	2º ano - Turma 22','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49410	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49416	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49422	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49428	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49434	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49440	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49446	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49452	,'TURMA'=>'62','DESCR_TURMA'=>'	6º ano - Turma 62','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49458	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49464	,'TURMA'=>'72','DESCR_TURMA'=>'	7º ano - Turma 72','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49470	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49476	,'TURMA'=>'82','DESCR_TURMA'=>'	8º ano - Turma 82','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49482	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49488	,'TURMA'=>'92','DESCR_TURMA'=>'	9º ano - Turma 92','escolas_id'=>7176,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49494	,'TURMA'=>'2º Manhã','DESCR_TURMA'=>'	2º ano - Turma Manhã','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49500	,'TURMA'=>'2º Tarde','DESCR_TURMA'=>'	2º ano - Turma Tarde','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49506	,'TURMA'=>'3º Manhã','DESCR_TURMA'=>'	3º ano - Turma Manhã','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49512	,'TURMA'=>'3º Tarde','DESCR_TURMA'=>'	3º ano - Turma Tarde','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49518	,'TURMA'=>'4º Manhã','DESCR_TURMA'=>'	4º ano - Turma Manhã','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49524	,'TURMA'=>'4º Tarde','DESCR_TURMA'=>'	4º ano - Turma Tarde','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49530	,'TURMA'=>'5º Tarde','DESCR_TURMA'=>'	5º ano - Turma Tarde','escolas_id'=>7170,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49536	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49542	,'TURMA'=>'22','DESCR_TURMA'=>'	2º ano - Turma 22','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49548	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49554	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49560	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49566	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49572	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49578	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49584	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49590	,'TURMA'=>'62','DESCR_TURMA'=>'	6º ano - Turma 62','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49596	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49602	,'TURMA'=>'72','DESCR_TURMA'=>'	7º ano - Turma 72','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49608	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49614	,'TURMA'=>'82','DESCR_TURMA'=>'	8º ano - Turma 82','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49620	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49626	,'TURMA'=>'92','DESCR_TURMA'=>'	9º ano - Turma 92','escolas_id'=>7140,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49632	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49638	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49644	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49650	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49656	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49662	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49668	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49674	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49680	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49686	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7146,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49692	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49698	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49704	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49710	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49716	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49722	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49728	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49734	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7182,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49740	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49746	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49752	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49758	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49764	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49770	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49776	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49782	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7152,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49788	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49794	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49800	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49806	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49812	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49818	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49824	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49830	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7188,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49836	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49842	,'TURMA'=>'22','DESCR_TURMA'=>'	2º ano - Turma 22','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49848	,'TURMA'=>'23','DESCR_TURMA'=>'	2º ano - Turma 23','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49854	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49860	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49866	,'TURMA'=>'33','DESCR_TURMA'=>'	3º ano - Turma 33','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49872	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49878	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49884	,'TURMA'=>'43','DESCR_TURMA'=>'	4º ano - Turma 43','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49890	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49896	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49902	,'TURMA'=>'53','DESCR_TURMA'=>'	5º ano - Turma 53','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49908	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49914	,'TURMA'=>'62','DESCR_TURMA'=>'	6º ano - Turma 62','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49920	,'TURMA'=>'63','DESCR_TURMA'=>'	6º ano - Turma 63','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49926	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49932	,'TURMA'=>'72','DESCR_TURMA'=>'	7º ano - Turma 72','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49938	,'TURMA'=>'73','DESCR_TURMA'=>'	7º ano - Turma 73','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49944	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49950	,'TURMA'=>'82','DESCR_TURMA'=>'	8º ano - Turma 82','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49956	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49962	,'TURMA'=>'92','DESCR_TURMA'=>'	9º ano - Turma 92','escolas_id'=>7164,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49968	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49974	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49980	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49986	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49992	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49998	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	50004	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	50010	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	50016	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7158,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48810	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48816	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49278	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48822	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48828	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49284	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48834	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48840	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48846	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48852	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>3594,'escolas_municipios_id'=>4	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49314	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49320	,'TURMA'=>'22','DESCR_TURMA'=>'	2º ano - Turma 22','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49326	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49332	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49338	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49344	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49350	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49356	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49362	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49368	,'TURMA'=>'62','DESCR_TURMA'=>'	6º ano - Turma 62','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49374	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49380	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49386	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49392	,'TURMA'=>'92','DESCR_TURMA'=>'	9º ano - Turma 92','escolas_id'=>1170,'escolas_municipios_id'=>2	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49068	,'TURMA'=>'Turma 2º','DESCR_TURMA'=>'	2º ano - Turma integral','escolas_id'=>7110,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49074	,'TURMA'=>'Turma 3º','DESCR_TURMA'=>'	3º ano - Turma integral','escolas_id'=>7110,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49080	,'TURMA'=>'Turma 4º','DESCR_TURMA'=>'	4º ano - Turma integral','escolas_id'=>7110,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49086	,'TURMA'=>'Turma 5º','DESCR_TURMA'=>'	5º ano - Turma integral','escolas_id'=>7110,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49092	,'TURMA'=>'Turma 2º','DESCR_TURMA'=>'	2º ano - Turma Tarde','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49098	,'TURMA'=>'Turma 3º','DESCR_TURMA'=>'	3º ano - Turma Tarde','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49104	,'TURMA'=>'Turma 4º','DESCR_TURMA'=>'	4º ano - Turma Tarde','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49110	,'TURMA'=>'Turma 5º','DESCR_TURMA'=>'	5º ano - Turma Manhã','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49116	,'TURMA'=>'Turma 6º','DESCR_TURMA'=>'	6º ano - Turma Manhã','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49122	,'TURMA'=>'Turma 7º','DESCR_TURMA'=>'	7º ano - Turma Manhã','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49128	,'TURMA'=>'Turma 8º','DESCR_TURMA'=>'	8º ano - Turma Manhã','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49134	,'TURMA'=>'Turma 9º','DESCR_TURMA'=>'	9º ano - Turma Manhã','escolas_id'=>7122,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49140	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49146	,'TURMA'=>'22','DESCR_TURMA'=>'	2º ano - Turma 22','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49152	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49158	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49164	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49170	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49176	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49182	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49188	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49194	,'TURMA'=>'62','DESCR_TURMA'=>'	6º ano - Turma 62','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49200	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49206	,'TURMA'=>'72','DESCR_TURMA'=>'	7º ano - Turma 72','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49212	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49218	,'TURMA'=>'82','DESCR_TURMA'=>'	8º ano - Turma 82','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49224	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49230	,'TURMA'=>'92','DESCR_TURMA'=>'	9º ano - Turma 92','escolas_id'=>7128,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49236	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>7134,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49242	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>7134,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49248	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>7134,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49254	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>7134,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49260	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>7134,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49290	,'TURMA'=>'Turma 2º','DESCR_TURMA'=>'	2º ano','escolas_id'=>7194,'escolas_municipios_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49296	,'TURMA'=>'Turma 3º','DESCR_TURMA'=>'	3º ano','escolas_id'=>7194,'escolas_municipios_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49302	,'TURMA'=>'Turma 4º','DESCR_TURMA'=>'	4º ano','escolas_id'=>7194,'escolas_municipios_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49308	,'TURMA'=>'Turma 5º','DESCR_TURMA'=>'	5º ano','escolas_id'=>7194,'escolas_municipios_id'=>1	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48858	,'TURMA'=>'21','DESCR_TURMA'=>'	2º ano - Turma 21','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48864	,'TURMA'=>'22','DESCR_TURMA'=>'	2º ano - Turma 22','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48870	,'TURMA'=>'23','DESCR_TURMA'=>'	2º ano - Turma 23','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48876	,'TURMA'=>'24','DESCR_TURMA'=>'	2º ano - Turma 24','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48882	,'TURMA'=>'25','DESCR_TURMA'=>'	2º ano - Turma 25','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48888	,'TURMA'=>'26','DESCR_TURMA'=>'	2º ano - Turma 26','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48912	,'TURMA'=>'31','DESCR_TURMA'=>'	3º ano - Turma 31','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48918	,'TURMA'=>'32','DESCR_TURMA'=>'	3º ano - Turma 32','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48924	,'TURMA'=>'33','DESCR_TURMA'=>'	3º ano - Turma 33','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48930	,'TURMA'=>'34','DESCR_TURMA'=>'	3º ano - Turma 34','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48936	,'TURMA'=>'35','DESCR_TURMA'=>'	3º ano - Turma 35','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48942	,'TURMA'=>'41','DESCR_TURMA'=>'	4º ano - Turma 41','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48948	,'TURMA'=>'42','DESCR_TURMA'=>'	4º ano - Turma 42','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48954	,'TURMA'=>'43','DESCR_TURMA'=>'	4º ano - Turma 43','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48960	,'TURMA'=>'44','DESCR_TURMA'=>'	4º ano - Turma 44','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48966	,'TURMA'=>'51','DESCR_TURMA'=>'	5º ano - Turma 51','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48972	,'TURMA'=>'52','DESCR_TURMA'=>'	5º ano - Turma 52','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48978	,'TURMA'=>'53','DESCR_TURMA'=>'	5º ano - Turma 53','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48984	,'TURMA'=>'54','DESCR_TURMA'=>'	5º ano - Turma 54','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48990	,'TURMA'=>'61','DESCR_TURMA'=>'	6º ano - Turma 61','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	48996	,'TURMA'=>'62','DESCR_TURMA'=>'	6º ano - Turma 62','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49002	,'TURMA'=>'63','DESCR_TURMA'=>'	6º ano - Turma 63','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49008	,'TURMA'=>'71','DESCR_TURMA'=>'	7º ano - Turma 71','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49014	,'TURMA'=>'72','DESCR_TURMA'=>'	7º ano - Turma 72','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49020	,'TURMA'=>'73','DESCR_TURMA'=>'	7º ano - Turma 73','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49026	,'TURMA'=>'81','DESCR_TURMA'=>'	8º ano - Turma 81','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49032	,'TURMA'=>'82','DESCR_TURMA'=>'	8º ano - Turma 82','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49038	,'TURMA'=>'83','DESCR_TURMA'=>'	8º ano - Turma 83','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49044	,'TURMA'=>'84','DESCR_TURMA'=>'	8º ano - Turma 84','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49050	,'TURMA'=>'91','DESCR_TURMA'=>'	9º ano - Turma 91','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49056	,'TURMA'=>'92','DESCR_TURMA'=>'	9º ano - Turma 92','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			
        DB::table('turmas')->insert(['id'=>	49062	,'TURMA'=>'93','DESCR_TURMA'=>'	9º ano - Turma 93','escolas_id'=>3246,'escolas_municipios_id'=>3	, 'created_at'=>Carbon::now(), 'updated_at'=> Carbon::now()]);			

    }
}
